### ISSUE TITLE
Updates for next iteration

### ISSUE THREAD

**Issue by nick-ulle** [ucdavisdatalab/workshop_intro_to_remote_computing#1]
Things we need to update:

- As far as I can tell, the reader doesn't mention `ssh-copy-id` or how to get a key onto a server

**Comment by PLNReynolds** [comment]
Add cli command?
pbcopy < ~/.ssh/id_rsa.pub

**Comment by nick-ulle** [comment]
Both are now in the reader, so marking this as closed.
